        "python is awesome"
        "hello world"
        "we are learning python"
        "we will meet tomorrow"

In [1]:
corpus = [
    "python is awesome",
    "hello world",
    "we are learning python",
    "we will meet tomorrow"
]

In [2]:
vocab = []
for document in corpus:
    for word in document.split():
        if word not in vocab:
            vocab.append(word)

In [4]:
vocab

['python',
 'is',
 'awesome',
 'hello',
 'world',
 'we',
 'are',
 'learning',
 'will',
 'meet',
 'tomorrow']

    word to vector

    vector to word

    {'python': 0, 'hello':1}

    {0:'python', 1:'hello'}

In [7]:
vocab = []
for document in corpus:
    for word in document.split():
        if word not in vocab:
            vocab.append(word)
vocab.sort()
vocab

['are',
 'awesome',
 'hello',
 'is',
 'learning',
 'meet',
 'python',
 'tomorrow',
 'we',
 'will',
 'world']

In [8]:
print(vocab)

['are', 'awesome', 'hello', 'is', 'learning', 'meet', 'python', 'tomorrow', 'we', 'will', 'world']


In [9]:
for i in enumerate(vocab):
    print(i)

(0, 'are')
(1, 'awesome')
(2, 'hello')
(3, 'is')
(4, 'learning')
(5, 'meet')
(6, 'python')
(7, 'tomorrow')
(8, 'we')
(9, 'will')
(10, 'world')


In [10]:
print(vocab)

['are', 'awesome', 'hello', 'is', 'learning', 'meet', 'python', 'tomorrow', 'we', 'will', 'world']


In [11]:
v = {w:v for v, w in enumerate(vocab)}

In [12]:
v

{'are': 0,
 'awesome': 1,
 'hello': 2,
 'is': 3,
 'learning': 4,
 'meet': 5,
 'python': 6,
 'tomorrow': 7,
 'we': 8,
 'will': 9,
 'world': 10}

In [13]:
def vocab(corpus):
    vocab = []
    for document in corpus:
        for word in document.split():
            if word not in vocab:
                vocab.append(word)
    vocab.sort()
    v = {w:v for v, w in enumerate(vocab)}
    return v

In [14]:
vocabulary = vocab(corpus)
vocabulary

{'are': 0,
 'awesome': 1,
 'hello': 2,
 'is': 3,
 'learning': 4,
 'meet': 5,
 'python': 6,
 'tomorrow': 7,
 'we': 8,
 'will': 9,
 'world': 10}

In [16]:
corpus

['python is awesome',
 'hello world',
 'we are learning python',
 'we will meet tomorrow']

In [17]:
len(vocabulary)

11

In [18]:
def bag_of_word(corpus, vocabulary):
    vectors = []
    for document in corpus:
        vector = [0] * len(vocabulary)
        for word in document.split():
            if word in vocabulary:
                i = vocabulary[word]
                vector[i] += 1
        vectors.append(vector)
    return vectors

In [19]:
bag_of_word(corpus, vocabulary)

[[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0]]

In [21]:
df = bag_of_word(corpus, vocabulary)
df

[[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0]]

In [20]:
import pandas as pd

In [22]:
pd.DataFrame(df, columns=vocabulary.keys())

,are,awesome,hello,is,learning,meet,python,tomorrow,we,will,world
0,0,1,0,1,0,0,1,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,1
2,1,0,0,0,1,0,1,0,1,0,0
3,0,0,0,0,0,1,0,1,1,1,0


In [17]:
[0] * 10

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [23]:
from sklearn.base import BaseEstimator, TransformerMixin

In [30]:
class Vectorization(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.vocab_ = None
        self.vocab_size_ = None

    def fit(self, corpus):
        vocab = []
        for document in corpus:
            for word in document.split():
                if word not in vocab:
                    vocab.append(word)
        vocab.sort()
        self.vocab_ = {w:v for v, w in enumerate(vocab)}
        self.vocab_size_ = len(self.vocab_)

    def transform(self, corpus):
        vectors = []
        for document in corpus:
            vector = [0] * self.vocab_size_
            for word in document.split():
                if word in self.vocab_:
                    i = self.vocab_[word]
                    vector[i] += 1
            vectors.append(vector)
        return vectors

In [31]:
vectors = Vectorization()

In [32]:
vectors

Vectorization()

In [33]:
vectors.fit(corpus)

In [34]:
vectors.transform(corpus)

[[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0]]

In [35]:
corpus = [
    "python is awesome awesome awesome",
    "hello world",
    "we are learning python",
    "we will meet tomorrow"
]

In [36]:
vectors.transform(corpus)

[[0, 3, 0, 1, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0]]

In [37]:
vectors.vocab_

{'are': 0,
 'awesome': 1,
 'hello': 2,
 'is': 3,
 'learning': 4,
 'meet': 5,
 'python': 6,
 'tomorrow': 7,
 'we': 8,
 'will': 9,
 'world': 10}

In [38]:
corpus = [
    "python is awesome",
    "hello world",
    "we are learning python",
    "we will meet tomorrow",
    "I am going to jaipur"
]

In [39]:
vectors.transform(corpus)

[[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [40]:
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
v = CountVectorizer()

In [42]:
v

CountVectorizer()

In [43]:
corpus = [
    "python is awesome",
    "hello world",
    "we are learning python",
    "we will meet tomorrow"
]

In [44]:
v.fit(corpus)

CountVectorizer()

In [45]:
v.vocabulary_

{'python': 6,
 'is': 3,
 'awesome': 1,
 'hello': 2,
 'world': 10,
 'we': 8,
 'are': 0,
 'learning': 4,
 'will': 9,
 'meet': 5,
 'tomorrow': 7}

In [46]:
sp_mx = v.transform(corpus)
sp_mx

<4x11 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [47]:
sp_mx.toarray()

array([[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0]], dtype=int64)

    Data Preprocessing: 

                1. Removing Stop words
                2. Removing special char.
                3. Stemming
                4. TF / IDF

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
data = pd.read_csv('spam.csv', encoding='latin', usecols=[0, 1])
data.rename({'v1':'label', 'v2':'message'}, axis=1, inplace=True)

In [27]:
data

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will Ì_ b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [28]:
X = data['message']

In [29]:
X = data['message'].str.lower()
X

0       go until jurong point, crazy.. available only ...
1                           ok lar... joking wif u oni...
2       free entry in 2 a wkly comp to win fa cup fina...
3       u dun say so early hor... u c already then say...
4       nah i don't think he goes to usf, he lives aro...
                              ...                        
5567    this is the 2nd time we have tried 2 contact u...
5568                will ì_ b going to esplanade fr home?
5569    pity, * was in mood for that. so...any other s...
5570    the guy did some bitching but i acted like i'd...
5571                           rofl. its true to its name
Name: message, Length: 5572, dtype: object

In [30]:
y = data['label']
y

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

In [32]:
vector = CountVectorizer()
vector.fit(X)
X_tr = vector.transform(X)

In [33]:
X_tr

<5572x8672 sparse matrix of type '<class 'numpy.int64'>'
	with 73916 stored elements in Compressed Sparse Row format>

In [34]:
X_tr.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
vector.vocabulary_

{'go': 3550,
 'until': 8030,
 'jurong': 4350,
 'point': 5920,
 'crazy': 2327,
 'available': 1303,
 'only': 5537,
 'in': 4087,
 'bugis': 1751,
 'great': 3634,
 'world': 8489,
 'la': 4476,
 'buffet': 1749,
 'cine': 2048,
 'there': 7645,
 'got': 3594,
 'amore': 1069,
 'wat': 8267,
 'ok': 5504,
 'lar': 4512,
 'joking': 4318,
 'wif': 8392,
 'oni': 5533,
 'free': 3358,
 'entry': 2949,
 'wkly': 8447,
 'comp': 2165,
 'to': 7756,
 'win': 8405,
 'fa': 3087,
 'cup': 2386,
 'final': 3207,
 'tkts': 7743,
 '21st': 411,
 'may': 4930,
 '2005': 402,
 'text': 7595,
 '87121': 784,
 'receive': 6297,
 'question': 6190,
 'std': 7230,
 'txt': 7933,
 'rate': 6242,
 'apply': 1156,
 '08452810075over18': 77,
 'dun': 2802,
 'say': 6633,
 'so': 7024,
 'early': 2823,
 'hor': 3927,
 'already': 1042,
 'then': 7640,
 'nah': 5238,
 'don': 2712,
 'think': 7660,
 'he': 3781,
 'goes': 3558,
 'usf': 8075,
 'lives': 4665,
 'around': 1207,
 'here': 3831,
 'though': 7680,
 'freemsg': 3365,
 'hey': 3841,
 'darling': 2443,
 'it

In [36]:
from sklearn.naive_bayes import MultinomialNB

In [38]:
model = MultinomialNB()
model.fit(X_tr, y)
y_hat = model.predict(X_tr)

In [39]:
y_hat

array(['ham', 'ham', 'spam', ..., 'ham', 'ham', 'ham'], dtype='<U4')

In [40]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [41]:
print(f"Accuracy Score: {accuracy_score(y, y_hat)}")

Accuracy Score: 0.9935391241923905


In [53]:
y

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

In [54]:
y.value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [42]:
print(f"Confusion matrix:\n {confusion_matrix(y, y_hat)}")

Confusion matrix:
 [[4812   13]
 [  23  724]]


In [56]:
from sklearn.model_selection import StratifiedShuffleSplit

In [57]:
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=123)

In [58]:
(train_idx, test_idx), = split.split(X, y)

In [59]:
train_idx

array([4128,  134, 2360, ..., 4344, 3697, 3389], dtype=int64)

In [60]:
test_idx

array([4574, 2858, 2515, ..., 3891,  436, 1953], dtype=int64)

In [61]:
X_train = X[train_idx]
X_test = X[test_idx]
y_train = y[train_idx]
y_test = y[test_idx]

In [62]:
from sklearn.pipeline import Pipeline

In [63]:
model = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('classification', MultinomialNB())
])

In [64]:
model.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('classification', MultinomialNB())])

In [65]:
y_hat_train = model.predict(X_train)
y_hat_test = model.predict(X_test)

In [66]:
y_hat_train

array(['ham', 'spam', 'ham', ..., 'ham', 'ham', 'spam'], dtype='<U4')

In [67]:
y_hat_test

array(['ham', 'ham', 'ham', ..., 'spam', 'ham', 'ham'], dtype='<U4')

In [68]:
def evaluate(y, y_hat):
    print(f"Accuracy Score: {accuracy_score(y, y_hat):.2f}\n")
    print(f"Confusion Matrix:\n {confusion_matrix(y, y_hat)}\n")
    print(f"Classification Report:\n {classification_report(y, y_hat)} ")

In [69]:
evaluate(y_train, y_hat_train)

Accuracy Score: 0.99

Confusion Matrix:
 [[3852    7]
 [  17  581]]

Classification Report:
               precision    recall  f1-score   support

         ham       1.00      1.00      1.00      3859
        spam       0.99      0.97      0.98       598

    accuracy                           0.99      4457
   macro avg       0.99      0.98      0.99      4457
weighted avg       0.99      0.99      0.99      4457
 


In [70]:
y_train.value_counts()

label
ham     3859
spam     598
Name: count, dtype: int64

In [71]:
evaluate(y_test, y_hat_test)


Accuracy Score: 0.99

Confusion Matrix:
 [[961   5]
 [ 10 139]]

Classification Report:
               precision    recall  f1-score   support

         ham       0.99      0.99      0.99       966
        spam       0.97      0.93      0.95       149

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115
 
